AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  calendar-api backend API
  
Globals:
  Function:
    Runtime: nodejs10.x
    Timeout: 5
    MemorySize: 256
    Layers:
        - !Ref BaseLayer
    

Resources:
  EchoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/echo/
      Handler: index.lambdaHandler
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /echo
            Method: get

  GetEvents:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/get-events/
      Handler: index.lambdaHandler
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /events
            Method: get


### ================
### Layers
### ================

  BaseLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: base-layer
      Description: Dependencies for Cognito
      ContentUri: ./src/layers/base/
      CompatibleRuntimes:
        - nodejs10.x
      LicenseInfo: "MIT"
      RetentionPolicy: Retain

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
